app.controller("shopownerlogin",function($scope,$http,$location){
    $scope.shopownerlogin=function(){
        //ajax.post("api/login",$scope.data,function(resp){},function(err){});
        $http.post("https://localhost:44360/api/Shop/Login",$scope.data)
        .then(function(resp){
            console.log(resp.data);
            localStorage.setItem("token",resp.data.AccessToken);
            $location.path("/Shopowner/Home");
        },function(err){
            console.log(err);
        });
    };
  });